#!/bin/bash

bash scripts/run_parcopose.bash
bash scripts/run_parcopose_h36m.bash
bash scripts/run_parcopose_h36m_uniformsampling.bash
bash scripts/run_parcopose_h36m_fixedrandomsampling.bash
bash scripts/run_parcopose_h36m_fixedconfidencesampling.bash
bash scripts/run_parcopose_h36m_fixedmpjpesampling.bash
